services:
  - type: web
    name: prod-backend
    runtime: image
    plan: free
    image:
      url: ghcr.io/pax-fin/be-app:v0.0.1
      creds:
        fromRegistryCreds:
          name: paxfin-ghcr
  - type: web
    name: prod-frontend
    runtime: image
    plan: free
    image:
      url: ghcr.io/pax-fin/fe-app:v0.0.2
      creds:
        fromRegistryCreds:
          name: paxfin-ghcr
